# 로컬 개발 환경 설정
spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:file:./data/testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 데이터 유지하면서 스키마 변경
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # 파일 업로드 경로
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 파일 업로드 디렉토리 (로컬 개발용)
file:
  upload:
    dir: ${user.dir}/uploads

# 서버 설정
server:
  port: 8080

# 로깅 설정
logging:
  level:
    com.fileextension.proj: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 